# Read the Docs configuration file
version: 2

sphinx:
  builder: html
  configuration: doc/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  system_packages: True
  install:
    - method: pip
      path: .
      extra_requirements:
        - lotkavolterra_example
        - docs
